"""
libreldr_entries.py

Single source of truth for libreldr boot entries. yeti-build's Stage 7
imports this from the cloned libreldr repo and calls the two renderers
to generate both backend configs:
  - libreldr.conf  (UEFI side, read by libreldr.efi)
  - syslinux.cfg   (BIOS side, read by syslinux/menu.c32)
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    title: str
    options: str  # kernel command line


ENTRIES = [
    Entry("YetiOS",                                   "root=LABEL=yetios-root ro quiet"),
    Entry("YetiOS (Debug)",                           "root=LABEL=yetios-root rw debug"),
    Entry("YetiOS (Log file)",                        "root=LABEL=yetios-root ro console=ttyS0,115200"),
    Entry("YetiOS (RAM Disk)",                        "root=/dev/ram0 init=/sbin/init"),
    Entry("YetiOS (Emergency Management Services)",   "root=LABEL=yetios-root ro single"),
]

TIMEOUT_SECONDS = 5
DEFAULT_INDEX = 0
INITRD = "initramfs.img"


def render_libreldr_conf() -> str:
    """UEFI config consumed by libreldr.efi."""
    lines = [
        "# libreldr -- UEFI configuration",
        "# Generated by yeti-build. Do not edit by hand.",
        "",
        f"timeout {TIMEOUT_SECONDS}",
        f"default {DEFAULT_INDEX}",
        "",
    ]
    for e in ENTRIES:
        lines += [
            f"title {e.title}",
            "linux \\EFI\\yetios\\vmlinuz.efi",
            f"options {e.options}",
            "",
        ]
    return "\n".join(lines)


def render_syslinux_cfg() -> str:
    """BIOS config consumed by syslinux/menu.c32, themed to mirror FreeLdr MinimalUI.

    syslinux menu.c32 layout constraints vs ReactOS FreeLdr:
      - Highlight bar always spans MENU WIDTH (no text-hugging).
        We set WIDTH to longest_entry + 4 to keep it tight.
      - TABMSG is a single line; ReactOS has two lines.
        We combine them: "Use ^ and v ... Press ENTER to choose."
      - F8 footer: menu.c32 has no "footer" directive.
        We place it as a MENU DISABLED entry after a separator.
    """
    longest = max(len(e.title) for e in ENTRIES)
    # Highlight bar: 4-space indent + title + 2 pad
    bar_width = longest + 6

    num = len(ENTRIES)
    # Row math: title at row 0, entries start row 2, then status text below.
    tabmsg_row   = num + 3
    timeout_row  = num + 5
    # Total entry rows includes real entries + separator + F8 disabled label.
    menu_rows    = num + 3  # entries + separator + blank + F8 line

    lines = [
        "# libreldr -- BIOS configuration (syslinux/menu.c32)",
        "# Generated by yeti-build. Do not edit by hand.",
        "",
        "UI menu.c32",
        f"DEFAULT {ENTRIES[DEFAULT_INDEX].title}",
        f"TIMEOUT {TIMEOUT_SECONDS * 10}",
        "PROMPT 0",
        "",
        # --- Layout ---
        "MENU TITLE Please select the operating system to start:",
        "MENU CLEAR",
        f"MENU ROWS {menu_rows}",
        f"MENU TABMSGROW {tabmsg_row}",
        f"MENU TIMEOUTROW {timeout_row}",
        "",
        # Left-align everything.
        "MENU VSHIFT 0",
        "MENU HSHIFT 0",
        f"MENU WIDTH {bar_width}",
        "MENU MARGIN 4",
        "MENU INDENT 0",
        "",
        # --- Colors: black bg, light-gray text, inverse highlight ---
        # Format: attr foreground background shadow
        "MENU COLOR screen       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR border       30;40  #00000000 #00000000 none",
        "MENU COLOR title        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR unsel        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR sel          30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR hotkey       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR hotsel       30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR tabmsg       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout_msg  37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR help         37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR disabled     37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR scrollbar    37;40  #00000000 #00000000 none",
        "",
        # --- Status text ---
        # ReactOS has two lines; menu.c32 TABMSG is one line.
        "MENU TABMSG Use ^ and v to move the highlight to your choice. Press ENTER to choose.",
        "MENU TIMEOUTMSG Seconds until highlighted choice will be started automatically: #",
        "",
    ]

    # --- Boot entries ---
    for e in ENTRIES:
        lines += [
            f"LABEL {e.title}",
            f"    MENU LABEL {e.title}",
            "    KERNEL /vmlinuz",
            f"    INITRD /{INITRD}",
            f"    APPEND {e.options}",
            "",
        ]

    # --- F8 footer as a disabled entry after a separator ---
    lines += [
        "MENU SEPARATOR",
        "",
        "LABEL f8_hint",
        "    MENU LABEL For troubleshooting and advanced startup options for YetiOS, press F8.",
        "    MENU DISABLED",
        "",
    ]

    return "\n".join(lines)