"""
libreldr_entries.py

Single source of truth for libreldr boot entries. yeti-build's Stage 7
imports this from the cloned libreldr repo and calls the two renderers
to generate both backend configs:
  - libreldr.conf  (UEFI side, read by libreldr.efi)
  - syslinux.cfg   (BIOS side, read by syslinux/menu.c32)
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    title: str
    options: str  # kernel command line


ENTRIES = [
    Entry("YetiOS",                                   "root=LABEL=yetios-root ro quiet"),
    Entry("YetiOS (Debug)",                           "root=LABEL=yetios-root rw debug"),
    Entry("YetiOS (Log file)",                        "root=LABEL=yetios-root ro console=ttyS0,115200"),
    Entry("YetiOS (RAM Disk)",                        "root=/dev/ram0 init=/sbin/init"),
    Entry("YetiOS (Emergency Management Services)",   "root=LABEL=yetios-root ro single"),
]

TIMEOUT_SECONDS = 5
DEFAULT_INDEX = 0
INITRD = "initramfs.img"


def render_syslinux_cfg() -> str:
    """BIOS config consumed by syslinux/menu.c32, themed to mirror FreeLdr MinimalUI.

    Known menu.c32 limitations vs ReactOS FreeLdr:
      - Title is always centered (no left-align option).
      - TABMSG is single-line only.
      - No bottom-of-screen footer.
    These cannot be fixed without replacing menu.c32 with a custom comboot.
    """
    num = len(ENTRIES)

    # Row layout (0-indexed, 25-row standard text mode):
    #   row 1:  MENU TITLE (centered by menu.c32, can't be helped)
    #   row 3:  first entry
    #   ...
    #   row 3+num-1: last entry
    #   row 3+num+1: TABMSG (single line)
    #   row 3+num+3: TIMEOUTMSG countdown
    #   row 23: F8 hint via HELPMSG
    entries_first_row = 3
    tabmsg_row   = entries_first_row + num + 1
    timeout_row  = tabmsg_row + 2
    helpmsg_row  = 23

    lines = [
        "# libreldr -- BIOS configuration (syslinux/menu.c32)",
        "# Generated by yeti-build. Do not edit by hand.",
        "",
        "UI menu.c32",
        f"DEFAULT {ENTRIES[DEFAULT_INDEX].title}",
        f"TIMEOUT {TIMEOUT_SECONDS * 10}",
        "PROMPT 0",
        "",
        # --- Layout ---
        "MENU TITLE Please select the operating system to start:",
        "MENU CLEAR",
        f"MENU ROWS {num}",                # MUST equal number of entries
        f"MENU TABMSGROW {tabmsg_row}",
        f"MENU TIMEOUTROW {timeout_row}",
        f"MENU HELPMSGROW {helpmsg_row}",
        f"MENU HELPMSGENDROW {helpmsg_row}",
        "",
        "MENU VSHIFT 1",
        "MENU HSHIFT 0",
        "MENU WIDTH 78",
        "MENU MARGIN 0",
        "MENU HIDDEN",
        "",
        # --- Colors ---
        "MENU COLOR screen       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR border       30;40  #00000000 #00000000 none",
        "MENU COLOR title        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR unsel        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR sel          30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR hotkey       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR hotsel       30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR tabmsg       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout_msg  37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR help         37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR disabled     37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR cmdmark      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR cmdline      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR scrollbar    37;40  #00000000 #00000000 none",
        "",
        # Single-line tabmsg (menu.c32 limitation).
        "MENU TABMSG Use ^ and v to move the highlight to your choice.  Press ENTER to choose.",
        "MENU TIMEOUTMSG Seconds until highlighted choice will be started automatically: #",
        "",
    ]

    # --- Boot entries (each gets the F8 footer as its HELPMSG) ---
    f8_msg = "For troubleshooting and advanced startup options for YetiOS, press F8."
    for e in ENTRIES:
        lines += [
            f"LABEL {e.title}",
            f"    MENU LABEL {e.title}",
            "    KERNEL /vmlinuz",
            f"    INITRD /{INITRD}",
            f"    APPEND {e.options}",
            "    TEXT HELP",
            f"{f8_msg}",
            "    ENDTEXT",
            "",
        ]

    return "\n".join(lines)