"""
libreldr_entries.py

Single source of truth for libreldr boot entries. yeti-build's Stage 7
imports this from the cloned libreldr repo and calls the two renderers
to generate both backend configs:
  - libreldr.conf  (UEFI side, read by libreldr.efi)
  - syslinux.cfg   (BIOS side, read by syslinux/menu.c32)
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    title: str
    options: str  # kernel command line


ENTRIES = [
    Entry("YetiOS",                                   "root=LABEL=yetios-root ro quiet"),
    Entry("YetiOS (Debug)",                           "root=LABEL=yetios-root rw debug"),
    Entry("YetiOS (Log file)",                        "root=LABEL=yetios-root ro console=ttyS0,115200"),
    Entry("YetiOS (RAM Disk)",                        "root=/dev/ram0 init=/sbin/init"),
    Entry("YetiOS (Emergency Management Services)",   "root=LABEL=yetios-root ro single"),
]

TIMEOUT_SECONDS = 5
DEFAULT_INDEX = 0
INITRD = "initramfs.img"


def render_libreldr_conf() -> str:
    """UEFI config consumed by libreldr.efi."""
    lines = [
        "# libreldr -- UEFI configuration",
        "# Generated by yeti-build. Do not edit by hand.",
        "",
        f"timeout {TIMEOUT_SECONDS}",
        f"default {DEFAULT_INDEX}",
        "",
    ]
    for e in ENTRIES:
        lines += [
            f"title {e.title}",
            "linux \\EFI\\yetios\\vmlinuz.efi",
            f"options {e.options}",
            "",
        ]
    return "\n".join(lines)


def render_syslinux_cfg() -> str:
    """BIOS config consumed by syslinux/menu.c32, themed to mirror FreeLdr MinimalUI."""
    num = len(ENTRIES)

    # Row layout (0-indexed):
    #   row 0:  MENU TITLE
    #   row 1:  blank
    #   rows 2..2+num-1: entries
    #   row 2+num:   blank
    #   row 2+num+1: "Use ^ and v to move the highlight to your choice."
    #   row 2+num+2: "Press ENTER to choose."
    #   row 2+num+3: blank
    #   row 2+num+4: "Seconds until highlighted choice..."
    entries_start = 2
    tabmsg_row    = entries_start + num + 1       # "Use ^ and v..."
    timeout_row   = tabmsg_row + 3                # countdown, 2 rows below tabmsg

    lines = [
        "# libreldr -- BIOS configuration (syslinux/menu.c32)",
        "# Generated by yeti-build. Do not edit by hand.",
        "",
        "UI menu.c32",
        f"DEFAULT {ENTRIES[DEFAULT_INDEX].title}",
        f"TIMEOUT {TIMEOUT_SECONDS * 10}",
        "PROMPT 0",
        "",
        # --- Layout ---
        # Title at col 0, row 0. Wide enough to never clip.
        "MENU TITLE Please select the operating system to start:",
        "MENU CLEAR",
        f"MENU ROWS {num}",
        f"MENU TABMSGROW {tabmsg_row}",
        f"MENU TIMEOUTROW {timeout_row}",
        "",
        # Left side of the screen, with ReactOS-like 4-space indent.
        "MENU VSHIFT 0",
        "MENU HSHIFT 0",
        "MENU WIDTH 78",      # full-width enough that title never clips
        "MENU MARGIN 4",      # 4-space indent before entries
        "MENU HIDDEN",        # hide title row's default decoration
        "",
        # --- Colors: black bg, light-gray fg, inverse highlight ---
        "MENU COLOR screen       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR border       30;40  #00000000 #00000000 none",
        "MENU COLOR title        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR unsel        37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR sel          30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR hotkey       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR hotsel       30;47  #ff000000 #ffaaaaaa none",
        "MENU COLOR tabmsg       37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout_msg  37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR timeout      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR help         37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR disabled     37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR cmdmark      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR cmdline      37;40  #ffaaaaaa #00000000 none",
        "MENU COLOR scrollbar    37;40  #00000000 #00000000 none",
        "",
        # --- Status text ---
        # menu.c32 only supports a SINGLE-LINE tabmsg. ReactOS has two lines.
        # We accept this limitation and put both phrases on one line.
        "MENU TABMSG Use ^ and v to move the highlight to your choice.  Press ENTER to choose.",
        "MENU TIMEOUTMSG Seconds until highlighted choice will be started automatically: #",
        "",
    ]

    # --- Boot entries ---
    for e in ENTRIES:
        lines += [
            f"LABEL {e.title}",
            f"    MENU LABEL {e.title}",
            "    KERNEL /vmlinuz",
            f"    INITRD /{INITRD}",
            f"    APPEND {e.options}",
            "",
        ]

    return "\n".join(lines)